export const INSTRUCTIONS = {
    START: 'Welcome! You are about to begin a task that evaluates facial-memory processing. You will first be asked to answer a few questions. Directly after, we will begin the two memory tests. This should take twenty minutes of undistracted time. Are you ready to begin?',
    T1_SLIDESHOW_1: 'Thank you! We are going to begin face-name memory test 1: Faces without context. Here, you will watch a slide-show of 36 faces - each appearing with their corresponding name for 5 seconds. After the slideshow, you will be asked to match names with the corresponding face appearing in the grid. You cannot take notes, but you may rely on mental strategies, especially if you do this during your own social endeavors. Remember, though you are being timed and your accuracy is being tallied, there is no reward for doing well. This is only for research purposes. Do you understand?',
    T1_SLIDESHOW_2: 'We will start with the 36 faces. You must try to remember each of their names. Are you ready to begin?',
    T1_SLIDESHOW_3: 'You’ve just finished seeing 36 faces, each paired with their name. Were you able to complete this task without distractions or interruptions?',
    T1_MATCHING_1: 'Now we are going to test your speed and accuracy by matching these names to their corresponding faces. Make sure all distractions are put away, and that you can perform this task uninterrupted, and to the fastest and best of your ability. But remember, there is no reward for doing well - this is only for research purposes. Do you understand?',
    T1_MATCHING_2: 'Were you able to finish the task uninterruptedly and without distractions?',
    T2_1: 'Great job! Thank you! Are you ready for the second and final test?',
    T2_2: 'Excellent! This version will be just like the prior test, but this time, each face will be paired with a descriptive sentence about the person. Just like the prior version, the goal is to test your face-name processing. You must ensure that all distractions are put away and that you can perform this task uninterruptedly. Are you ready to begin?',
    T2_3: 'Were you able to finish this second task uninterruptedly and without distractions?',
    POSTTRIAL_SURVEY: 'Hooray! Before we end this test, we have just a few quick questions that will also help us operationalize our data. Are you ready to answer?',
    END: <span>Thank you very much! Your participation in this study is aimed to help provide more insight into facial memory, face-name processing, upbringing, adoption, and developmental psychology. Your results are only viewable to yourself and the investigator of this study, who will only see your username. When this work is published, your name and specific information identifying you will not appear anywhere. If you have any questions about anything, please contact us at <a href="mailto:sarmen@fordham.edu">sarmen@fordham.edu</a>.</span>,
    QUIT: 'Thank you for your time and consideration.'
}